package org.citizen.sdk

/** Non-secret Core events emitted on one ordered executor. */
object CitizenSdkEvents {
    enum class TransferStatus {
        READY,
        BROADCAST,
        FUTURE,
        IN_BLOCK,
        FINALIZED,
        RETRACTED,
        FINALITY_TIMEOUT,
        DROPPED,
        INVALID,
        USURPED,
    }

    sealed class Event(open val sequence: String) {
        /** Invalidation only; query the existing history API for the current state. */
        class HistoryChanged(override val sequence: String) : Event(sequence)
        class LifecycleChanged(
            override val sequence: String,
            val lifecycle: CitizenSdkLifecycle,
        ) : Event(sequence)

        /** Carries the complete snapshot; consumers never race a follow-up query. */
        class CapabilitiesChanged(
            override val sequence: String,
            val capabilities: CitizenSdkCapabilities,
        ) : Event(sequence)

        /**
         * Exact submit/watch status for one facade operation.
         *
         * `operationId` is generated by the Kotlin facade before admission. It
         * is neither a C request ID nor a native/result handle. A Flutter host
         * registers its own request sequence against this value before it
         * forwards progress and therefore never guesses by FIFO order.
         */
        class TransferProgress(
            override val sequence: String,
            val operationId: String,
            val status: TransferStatus,
            val block: CitizenBlockRef?,
            replacementHash: ByteArray?,
            val peerCount: Long,
        ) : Event(sequence) {
            private val replacementValue = replacementHash?.requireSize(32, "replacementHash")
            fun replacementHash(): ByteArray? = replacementValue?.clone()
        }
    }

    fun interface Listener {
        fun onEvent(event: Event)
    }

    fun interface TransferProgressListener {
        fun onProgress(progress: Event.TransferProgress)
    }
}
